---
title: "trytidydata"
output: html_document
---

```{r}
library(readr)
library(ggplot2)
library(tidyverse)
library(lubridate)
readr::read_rds("DS_Final_App/data/tidy_covid19_case.rds") -> 
  covid19
```

```{r}
covid19 %>% 
  na_if("Missing") %>% 
  na_if("Unknown") %>% 
  mutate(case_month = ym(case_month)) %>% 
  mutate(age_group = str_replace(age_group, "to", "-"),
         age_group = str_replace(age_group, "years", "")) %>% 
  mutate(age_group = as.factor(age_group),
         sex = as.factor(sex),
         hosp_yn = as.factor(hosp_yn),
         icu_yn = as.factor(icu_yn),
         death_yn = as.factor(death_yn),
         underlying_conditions_yn = as.factor(underlying_conditions_yn))  ->
  covid19_tidy
```

```{r}
covid19_tidy %>% 
  filter(between(case_month, as.Date("2021-01-01"), as.Date("2021-03-01"))) %>% 
  arrange(case_month)
```

```{r}
covid19_tidy %>% 
  filter(between(case_month, as.Date("2020-05-01"), as.Date("2021-03-01"))) %>% 
  group_by(case_month, race) %>% 
  summarise(total_case = n(), .groups = "keep") %>% 
  ggplot(aes(x = case_month, y = total_case, color = race)) +
  geom_smooth(se = F)
```

```{r}
covid19_tidy %>% 
  count(res_state, name = "state_case_total") ->
  state_case_total_df

covid19_tidy %>% 
  count(race, res_state, name = "case_by_race_state") %>% 
  inner_join(state_case_total_df) %>% 
  mutate(dist = round(case_by_race_state/state_case_total, digits = 5)) %>% 
  filter(res_state == "CA")
```

```{r}
covid19_tidy %>% 
  group_by(case_month, race, res_state) %>% 
  summarise(total_case = n(), .groups = "keep") %>% 
  ggplot(aes(x = res_state, y = total_case, fill = race)) +
  geom_col() +
  coord_flip()
```

```{r}
covid19_tidy %>% 
  group_by(case_month, race, age_group) %>% 
  summarise(total_case = n(), .groups = "keep") %>% 
  drop_na(age_group) %>% 
  ggplot(aes(x = age_group, y = total_case, fill = race)) +
  geom_col()
```

```{r}
covid19_tidy %>% 
  filter(death_yn == "Yes") %>% 
  group_by(case_month, race, age_group) %>% 
  summarise(total_case = n(), .groups = "keep") %>% 
  drop_na(age_group) %>% 
  ggplot(aes(x = age_group, y = total_case, fill = race)) +
  geom_col()
```

```{r}
unique(covid19_tidy[c("res_state")])
```

