---
title: "data_by_state"
author: "Liu Chi Yun"
date: "4/25/2021"
output: pdf_document
---

```{r message=FALSE}
library(tidyverse)
library(lubridate)
```




```{r}
readr::read_rds("../data/tidy_covid19_case.rds") -> 
  covid19_data

covid19_data %>% 
  na_if("Missing") %>% 
  na_if("Unknown") %>% 
  mutate(case_month = ym(case_month)) %>% 
  mutate(age_group = str_replace(age_group, "to", "-"),
         age_group = str_replace(age_group, "years", "")) %>% 
  mutate(age_group = as.factor(age_group),
         sex = as.factor(sex),
         hosp_yn = as.factor(hosp_yn),
         icu_yn = as.factor(icu_yn),
         death_yn = as.factor(death_yn),
         underlying_conditions_yn = as.factor(underlying_conditions_yn))  ->
  covid19_tidy
```


```{r}
# reference
# https://www.kaggle.com/washimahmed/usa-latlong-for-state-abbreviations
# read state long/lat, merge long, lat for map, remove fips code
log_lat <- read_csv("../data/statelatlong.csv")
covid19_tidy %>% 
  select(-state_fips_code, -county_fips_code) 

# remove GU, VI, PR, 
setdiff(unique(covid19_tidy$res_state), unique(log_lat$State))
  
  
```







